name: Apexhost
favicon: null
layout_spectrum: 0.10448651132173836
typography_spectrum: 0.7721570001449436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9971285052597523
  lightness: 0.21550730057060719
  saturation: 0.7371221357025206
  rhythmicContrast: 0.36141524324193597
purpose: []
